services:
  backend:
    build: ./backend
    container_name: catfun-backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://admin:root@db:3306/catfun?serverVersion=8.0"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: catfun-frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: catfun-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catfun
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: catfun-nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  db_data:
